# Generated by Django 5.1.7 on 2025-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.IntegerField()),
                ('chapter', models.IntegerField()),
                ('line', models.IntegerField()),
                ('position', models.IntegerField()),
                ('token', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
    ]
